# Generated by Django 4.1.1 on 2022-09-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclassiffier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodels',
            old_name='weight',
            new_name='weights',
        ),
    ]
